name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
    - name: Checkout code
      users: actions/checkout@v4

    - name: Set up Python
      users: actions/setup-python@v5
      with:
        python-versoion: "3.10"

    - name: install dependencies
      run: |
        pip install pytest

    - name: Run tests
      run: |
      pytest || true  

